### ISSUE TITLE
Imagenet spearman calculation correlations

### ISSUE THREAD

**Issue by akhiad** [leeyeehoo/GenNAS#1]
Thanks for the very interesting work. I'm having a hard time finding the imagenet accuracies or ranks of networks used to calculate the spearman correlations for the NDS imagenet part of table 2 in the paper. When I download the NDS data from the link, I get a JSON per NAS space, but I can only find accuracies for CIFAR models there (as far as I understand). Can you please reference the right location?

**Comment by leeyeehoo** [comment]
Hi akhiad, imagenet JSON data named with*_in in the downloaded file.

**Comment by akhiad** [comment]
Thanks a lot again!
